#!/usr/bin/env bash
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

BUILD_DIR="$SCRIPT_DIR/build"
mkdir -p "$BUILD_DIR"

# Load environment variables / secrets from .env if present
if [ -f "$SCRIPT_DIR/.env" ]; then
    echo "=== Loading Secrets from .env ==="
    while IFS='=' read -r key value || [ -n "$key" ]; do
        key="$(echo "$key" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
        if [[ "$key" =~ ^#.*$ ]] || [ -z "$key" ]; then
            continue
        fi
        value="$(echo "$value" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' -e 's/^["'"'"']//' -e 's/["'"'"']$//')"
        export "$key"="$value"
    done < "$SCRIPT_DIR/.env"
fi

# Set default values if not defined in .env or environment
NEXTENDO_OAUTH_CLIENT_ID="${NEXTENDO_OAUTH_CLIENT_ID:-}"
NEXTENDO_SERVER_IP="${NEXTENDO_SERVER_IP:-127.0.0.1}"
NEXTENDO_NAT_IP="${NEXTENDO_NAT_IP:-127.0.0.1}"
NEXTENDO_SERVER_URL="${NEXTENDO_SERVER_URL:-https://nextendo.network}"
NEXTENDO_REDIRECT_URI="${NEXTENDO_REDIRECT_URI:-melonx://oauth/callback}"
NEXTENDO_OAUTH_SCOPES="${NEXTENDO_OAUTH_SCOPES:-identity friends presence game.matchmaking profil}"

# Generate NextendoSecrets.swift build constant file for Swift
SECRETS_SWIFT="$SCRIPT_DIR/src/src/MeloNX/MeloNX/NextendoSecrets.swift"
echo "=== Generating Nextendo Build Constants ($SECRETS_SWIFT) ==="
cat << EOF > "$SECRETS_SWIFT"
//
//  NextendoSecrets.swift
//  MeloNX
//
//  Auto-generated by build.sh from .env / CI secrets at build time.
//  Do NOT commit secrets to source control.
//

import Foundation

public enum NextendoSecrets {
    /// Hidden Nextendo OAuth Client ID extracted from .env build constant (empty if not configured)
    public static let oauthClientId: String = "${NEXTENDO_OAUTH_CLIENT_ID}"
    
    /// Indicates whether Nextendo OAuth is configured and enabled for this build
    public static var isOAuthEnabled: Bool {
        let trimmed = oauthClientId.trimmingCharacters(in: .whitespacesAndNewlines)
        return !trimmed.isEmpty && trimmed != "none"
    }
    
    /// Default Nextendo Game Server IP extracted from .env build constant (defaults to 127.0.0.1 if unconfigured)
    public static let defaultServerIp: String = "${NEXTENDO_SERVER_IP}"
    
    /// Default Nextendo NAT Responder IP extracted from .env build constant (defaults to 127.0.0.1 if unconfigured)
    public static let defaultNatIp: String = "${NEXTENDO_NAT_IP}"
    
    /// Default Nextendo Server URL extracted from .env build constant
    public static let defaultServerUrl: String = "${NEXTENDO_SERVER_URL}"
    
    /// Default Nextendo OAuth Redirect URI
    public static let defaultRedirectUri: String = "${NEXTENDO_REDIRECT_URI}"
    
    /// Nextendo OAuth requested scopes (all supported scopes except mods.favorites)
    public static let oauthScopes: String = "${NEXTENDO_OAUTH_SCOPES}"
}
EOF

echo "=== Building Real C# Ryujinx Core Library ==="
if [ -z "$DOTNET_ROOT" ] || [ ! -d "$DOTNET_ROOT" ]; then
    if [ -d "/usr/local/share/dotnet" ]; then
        export DOTNET_ROOT="/usr/local/share/dotnet"
    elif [ -d "$HOME/.dotnet" ]; then
        export DOTNET_ROOT="$HOME/.dotnet"
    fi
fi

if [ -n "$DOTNET_ROOT" ] && [ -d "$DOTNET_ROOT" ]; then
    export PATH="$DOTNET_ROOT:/opt/homebrew/bin:$PATH"
else
    export PATH="/usr/local/share/dotnet:/opt/homebrew/bin:$PATH"
fi

DOTNET_CMD="$(command -v dotnet || true)"
if [ -z "$DOTNET_CMD" ]; then
    for candidate in "$DOTNET_ROOT/dotnet" "/opt/homebrew/bin/dotnet" "/usr/local/share/dotnet/dotnet" "/usr/local/bin/dotnet" "$HOME/.dotnet/dotnet"; do
        if [ -n "$candidate" ] && [ -x "$candidate" ]; then
            DOTNET_CMD="$candidate"
            break
        fi
    done
fi

REAL_LIB=""
find_real_lib() {
    for candidate in \
        "src/src/Ryujinx.Library/bin/Release/net10.0/ios-arm64/publish/Ryujinx.Library.dylib" \
        "src/src/Ryujinx.Library/bin/Release/net10.0/ios-arm64/native/Ryujinx.Library.dylib" \
        "src/src/Ryujinx.Library/bin/Release/net8.0/ios-arm64/publish/Ryujinx.Library.dylib" \
        "src/src/Ryujinx.Library/bin/Release/net8.0/ios-arm64/native/Ryujinx.Library.dylib"; do
        if [ -f "$candidate" ]; then
            REAL_LIB="$candidate"
            return 0
        fi
    done
    return 1
}

if ! find_real_lib; then
    echo "Compiling C# NativeAOT emulator backend with .NET SDK..."
    if [ -n "$DOTNET_CMD" ]; then
        (cd src && "$DOTNET_CMD" publish -c Release -r ios-arm64 -p:ExtraDefineConstants=DISABLE_UPDATER src/Ryujinx.Library --self-contained true)
    else
        echo "ERROR: .NET SDK (dotnet) not found in PATH or standard directories."
        exit 1
    fi
    find_real_lib || true
fi

if [ -z "$REAL_LIB" ] || [ ! -f "$REAL_LIB" ]; then
    echo "ERROR: Real Ryujinx.Library.dylib was not found and could not be built."
    echo "Please ensure the .NET SDK is installed and run 'cd src && dotnet publish -c Release -r ios-arm64 -p:ExtraDefineConstants=DISABLE_UPDATER src/Ryujinx.Library --self-contained true'."
    exit 1
fi

echo "Using Real Ryujinx Core Library: $REAL_LIB"
LIB_DIR="src/src/Ryujinx.Library/bin/Release/net10.0/ios-arm64/native"
mkdir -p "$LIB_DIR"
cp "$REAL_LIB" "$LIB_DIR/Ryujinx.Library.dylib"
install_name_tool -id "@rpath/Ryujinx.Library.dylib" "$LIB_DIR/Ryujinx.Library.dylib" 2>/dev/null || true

DO_SIGN=false
CONFIGURATION="Debug"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --sign)
            DO_SIGN=true
            shift
            ;;
        --release)
            CONFIGURATION="Release"
            shift
            ;;
        --debug)
            CONFIGURATION="Debug"
            shift
            ;;
        --configuration|-c)
            CONFIGURATION="$2"
            shift 2
            ;;
        *)
            shift
            ;;
    esac
done

DEV_TEAM="${DEVELOPMENT_TEAM:-8Y564F7WGM}"

DERIVED_DATA_DIR="$BUILD_DIR/DerivedData"

if [ "$DO_SIGN" = true ]; then
    echo "=== Building MeloNX App (Signed, Config: $CONFIGURATION, Development Identity) ==="
    xcodebuild -project src/src/MeloNX/MeloNX.xcodeproj \
               -scheme MeloNX \
               -configuration "$CONFIGURATION" \
               -destination 'generic/platform=iOS' \
               -derivedDataPath "$DERIVED_DATA_DIR" \
               -allowProvisioningUpdates \
               CODE_SIGNING_ALLOWED=YES \
               CODE_SIGN_IDENTITY="Apple Development" \
               DEVELOPMENT_TEAM="$DEV_TEAM"
else
    echo "=== Building MeloNX App (Unsigned, Config: $CONFIGURATION) ==="
    xcodebuild -project src/src/MeloNX/MeloNX.xcodeproj \
               -scheme MeloNX \
               -configuration "$CONFIGURATION" \
               -destination 'generic/platform=iOS' \
               -derivedDataPath "$DERIVED_DATA_DIR" \
               CODE_SIGN_STYLE=Manual \
               CODE_SIGNING_ALLOWED=NO \
               CODE_SIGN_IDENTITY="" \
               CODE_SIGNING_REQUIRED=NO \
               DEVELOPMENT_TEAM="" \
               PROVISIONING_PROFILE_SPECIFIER=""
fi

APP_PATH="$DERIVED_DATA_DIR/Build/Products/${CONFIGURATION}-iphoneos/MeloNX.app"
if [ ! -d "$APP_PATH" ]; then
    APP_PATH="$(find "$DERIVED_DATA_DIR" -name "MeloNX.app" -type d | head -n 1)"
fi

if [ -n "$APP_PATH" ] && [ -d "$APP_PATH" ]; then
    if [ "$DO_SIGN" = true ]; then
        DEV_IDENTITY="$(security find-identity -p codesigning -v 2>/dev/null | grep "Apple Development" | head -n 1 | awk '{print $2}')"
        if [ -n "$DEV_IDENTITY" ]; then
            SIGN_ID="$DEV_IDENTITY"
        else
            SIGN_ID="$(codesign -dvv "$APP_PATH" 2>&1 | grep "Authority=" | head -n 1 | sed 's/Authority=//' || true)"
            if [ -z "$SIGN_ID" ]; then
                SIGN_ID="-"
            fi
        fi
    else
        SIGN_ID="-"
    fi

    rm -rf "$BUILD_DIR/MeloNX.app"
    cp -R "$APP_PATH" "$BUILD_DIR/MeloNX.app"
    
    echo "=== Embedding Ryujinx.Library.dylib in App Frameworks ==="
    mkdir -p "$BUILD_DIR/MeloNX.app/Frameworks"
    cp "$LIB_DIR/Ryujinx.Library.dylib" "$BUILD_DIR/MeloNX.app/Frameworks/Ryujinx.Library.dylib"
    install_name_tool -id @rpath/Ryujinx.Library.dylib "$BUILD_DIR/MeloNX.app/Frameworks/Ryujinx.Library.dylib" 2>/dev/null || true

    REAL_DIR="$(dirname "$REAL_LIB")"
    if [ -f "$REAL_DIR/libarmeilleure-jitsupport.dylib" ]; then
        cp "$REAL_DIR/libarmeilleure-jitsupport.dylib" "$BUILD_DIR/MeloNX.app/Frameworks/libarmeilleure-jitsupport.dylib"
        install_name_tool -id @rpath/libarmeilleure-jitsupport.dylib "$BUILD_DIR/MeloNX.app/Frameworks/libarmeilleure-jitsupport.dylib" 2>/dev/null || true
    fi

    install_name_tool -change "src/src/Ryujinx.Library/bin/Release/net10.0/ios-arm64/native/Ryujinx.Library.dylib" "@rpath/Ryujinx.Library.dylib" "$BUILD_DIR/MeloNX.app/MeloNX" 2>/dev/null || true
    install_name_tool -change "src/src/Ryujinx.Library/bin/Release/net10.0/ios-arm64/publish/Ryujinx.Library.dylib" "@rpath/Ryujinx.Library.dylib" "$BUILD_DIR/MeloNX.app/MeloNX" 2>/dev/null || true
    if [ -f "$BUILD_DIR/MeloNX.app/MeloNX.debug.dylib" ]; then
        install_name_tool -change "src/src/Ryujinx.Library/bin/Release/net10.0/ios-arm64/native/Ryujinx.Library.dylib" "@rpath/Ryujinx.Library.dylib" "$BUILD_DIR/MeloNX.app/MeloNX.debug.dylib" 2>/dev/null || true
        install_name_tool -change "src/src/Ryujinx.Library/bin/Release/net10.0/ios-arm64/publish/Ryujinx.Library.dylib" "@rpath/Ryujinx.Library.dylib" "$BUILD_DIR/MeloNX.app/MeloNX.debug.dylib" 2>/dev/null || true
    fi

    echo "=== Signing embedded frameworks with identity: $SIGN_ID ==="
    for item in "$BUILD_DIR/MeloNX.app/Frameworks/"*; do
        if [ -d "$item" ] || [[ "$item" == *.dylib ]]; then
            codesign --force --sign "$SIGN_ID" --timestamp=none "$item" 2>/dev/null || true
        fi
    done
    if [ -f "$BUILD_DIR/MeloNX.app/MeloNX.debug.dylib" ]; then
        codesign --force --sign "$SIGN_ID" --timestamp=none "$BUILD_DIR/MeloNX.app/MeloNX.debug.dylib" 2>/dev/null || true
    fi
    
    XCENT_PATH="$(find "$DERIVED_DATA_DIR/Build/Intermediates.noindex" -name "MeloNX.app.xcent" -type f | head -n 1)"
    if [ "$DO_SIGN" = true ] && [ -n "$XCENT_PATH" ] && [ -f "$XCENT_PATH" ]; then
        codesign --force --sign "$SIGN_ID" --timestamp=none --entitlements "$XCENT_PATH" "$BUILD_DIR/MeloNX.app" 2>/dev/null || true
    else
        codesign --force --sign "$SIGN_ID" --timestamp=none "$BUILD_DIR/MeloNX.app" 2>/dev/null || true
    fi

    echo "=== Packaging IPA ==="
    TMP_IPA_DIR="$(mktemp -d)"
    mkdir -p "$TMP_IPA_DIR/Payload"
    cp -R "$BUILD_DIR/MeloNX.app" "$TMP_IPA_DIR/Payload/"
    rm -f "$BUILD_DIR/MeloNX.ipa"
    (cd "$TMP_IPA_DIR" && zip -qr "$BUILD_DIR/MeloNX.ipa" Payload)
    rm -rf "$TMP_IPA_DIR"

    echo "=== Build Succeeded! ==="
    echo "App Bundle: $BUILD_DIR/MeloNX.app"
    echo "IPA File:   $BUILD_DIR/MeloNX.ipa"
else
    echo "Build completed, but MeloNX.app was not found in DerivedData."
fi
